title: Kit chooser
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: true
copyedit: true
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Create your kit
  - title: Make colour pickers
  - title: Draw a pattern
  - title: Add a button
  - title: Choose all the colours!
  - title: Challenge

